package woyou.aidlservice.jiuiv5;

import woyou.aidlservice.jiuiv5.IPrinterCallback;

interface IPrinterService {
    int getPrinterStatus();
    int printerInit();
    int sendRAWData(in byte[] data);
    int setAlignment(int alignment);
    int setFontSize(int size);
    int setFontType(int type);
    int setLineSpacing(int spacing);
    int setBold(boolean bold);
    int setUnderline(boolean underline);
    int setDoubleStrike(boolean doubleStrike);
    int setGrayLevel(int level);
    int setPaperType(int type);
    int printText(String text);
    int printTextWithFont(String text, String encoding, int fontSize, int fontStyle);
    int printTextSize(String text, int size, int style);
    int printOriginalText(String text, String encoding);
    int printColumnsText(in String[] cols, in int[] colsWidth, in int[] colsAlign);
    int printColumnsString(in String[] cols, in int[] colsWidth, in int[] colsAlign);
    int printBitmap(in android.graphics.Bitmap bitmap);
    int printBytes(in byte[] data);
    int printBase64Data(String data);
    int printXBitmap(String data, int width, int height);
    int printBarCode(String data, int symbology, int height, int width, int textPosition);
    int printQRCode(String data, int modulesize, int errorlevel);
    int print1DCode(String data, int symbology, int height, int width, int textPosition);
    int setCharacterSet(String charset);
    int setPrintSpeed(int speed);
    int setPrintDensity(int density);
    int exit();
    int openDrawer();
    int getDrawerStatus();
    int cutPaper(int cutter);
    int getCutPaperStatus();
    int lineWrap(int n);
    int setFontDirection(int direction);
    int setFontRotate90(boolean rotate);
    int setBlobData(in byte[] data);
    int setHorizontalPosition(int position);
    int setPrintDistance(int distance);
    void printTextWithCallback(String text, IPrinterCallback callback);
    void printTextWithFontWithCallback(String text, String encoding, int fontSize, int fontStyle, IPrinterCallback callback);
    void printColumnsTextWithCallback(in String[] cols, in int[] colsWidth, in int[] colsAlign, IPrinterCallback callback);
    void printBitmapWithCallback(in android.graphics.Bitmap bitmap, IPrinterCallback callback);
    void printBarCodeWithCallback(String data, int symbology, int height, int width, int textPosition, IPrinterCallback callback);
    void printQRCodeWithCallback(String data, int modulesize, int errorlevel, IPrinterCallback callback);
    void print1DCodeWithCallback(String data, int symbology, int height, int width, int textPosition, IPrinterCallback callback);
    void printOriginalTextWithCallback(String text, String encoding, IPrinterCallback callback);
    void printBytesWithCallback(in byte[] data, IPrinterCallback callback);
    void sendRAWDataWithCallback(in byte[] data, IPrinterCallback callback);
    int getPrinterServiceVersion();
    int getPrintedLength();
    int setLabelType(int type);
    int getLabelStatus();
    int getLabelSize();
}
